version: '3'

services:
  elections:
    build: 
      context: .
      dockerfile: ./Dockerfile
      args:
       - NODE_ENV:development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start